# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1213846c7314434df3488e58f776711c1f3d025bc4cfdff47f3d57ed5b43a3ba83113e2bde47f97e2fe5ca9cfcdafcfdba2c9f944af45e08949857af2e1877ea

test:
  secret_key_base: 74dd96ca1f8ddb471fe9a38dd0de218895443f8b2fc48adab05efc8f3d16047443ced8b6fb3d507ae36d81ff76ec00bb1f3a0686bd0ab625e604c2ff47d4f93c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
